### ISSUE TITLE
websocket 通过此插件认证失败

### ISSUE THREAD

**Issue by cjcj125125** [emqx/emqx-auth-username#101]
按照文档在emqx_auth_username.conf 中配置了账号密码，MQTT客户端通过此账号密码可以连接服务，但是websocket使用此账号密码不能连接，奇怪的是Dashboard控制台可以连接websocket服务，如下图所示，使用的是v3.0.1版本，希望得到你们的帮助，谢谢

![QQ截图20190427144734](https://user-images.githubusercontent.com/20206579/56846135-c903e100-68fd-11e9-9c3c-8554742b0d02.png)
![QQ截图20190427144815](https://user-images.githubusercontent.com/20206579/56846139-dae58400-68fd-11e9-94ec-720dcc6baf46.png)
![QQ截图20190427150400](https://user-images.githubusercontent.com/20206579/56846144-e9cc3680-68fd-11e9-9d38-aaac05ec9f74.png)
![QQ截图20190427150231](https://user-images.githubusercontent.com/20206579/56846150-f81a5280-68fd-11e9-91ea-c39cd80133c3.png)

**Comment by HJianBo** [comment]
Hi, @cjcj125125  Can you provide the started plugins list and the `allow_anonymous` option value in the `etc/emqx.conf`?

**Comment by cjcj125125** [comment]
![QQ截图20190429133539](https://user-images.githubusercontent.com/20206579/56877900-be735400-6a83-11e9-8fec-496caeca32f0.png)
能不能提供 websocket通过密码连接的demo？？谢谢

**Comment by HJianBo** [comment]
Sorry, we can't provide any demo for there. Just use the [MQTT.js](https://github.com/mqttjs/MQTT.js) library, if you wanna connect EMQ X broker over WebSocket.

It will be a very complex work to implement the MQTT Protocol on the low-level WebSocket APIs!

**Comment by cjcj125125** [comment]
那么我在java后台中可以使用MQTT.js嘛？？另外问一下，开启了emqx_auth_username插件，我需要怎么配置才可以使用emqx_auth_username 对应的http api接口呢？？例如：api/v3/auth_username

**Comment by HJianBo** [comment]
> 那么我在java后台中可以使用MQTT.js嘛？

Obviously not!

> 另外问一下，开启了emqx_auth_username插件，我需要怎么配置才可以使用emqx_auth_username 对应的http api接口呢？

Above v3.1-rc.2 version, you can refer to the [README](https://github.com/emqx/emqx-auth-username#rest-api) guide to learn how to use it 

Furthermore, I suggest that you can join our QQ Group(12222225) or Wechat group to get more convenience support for these questions.
