### ISSUE TITLE
请问 auth-username插件 在 emqx-websocket 协议上是否有效

### ISSUE THREAD

**Issue by sitsh** [emqx/emqx-auth-username#117]
环境 win2016
emqx 3.2.0 -win

通过 caddy.server 反代 emqx websocket ws 端口

仪表板开启 emqx-auth-username 插件
添加 用户
关闭 emqx 匿名登陆

通过 java 或 c# 客户端 连接服务器 emqx-auth-username 验证都生效 错误的用户密码 都被连接拒绝。
通过 emqx 仪表板  或第三方 mqtt.js  websocket 协议连接服务器  输入错误的用户名 和密码 都能 连接上服务器 验证插件感觉 没有在 websocket 这个协议上 生效。

请问 插件是否支持 websocket 协议的验证。

**Comment by HJianBo** [comment]
Hi @sitsh sorry too late reply there.

No authentication plug-in handles different protocols differently. So it works for WebSocket connections.
