### ISSUE TITLE
defalut username/password not disabling

### ISSUE THREAD

**Issue by sphonala** [emqx/emqx-auth-username#140]
Hi, I've install emqx server on aws instance, I've enabled emqx-auth-username plugin and updated with my 'username' and 'password' and removed default user 'admin'/'public123', but it still accepting connections on default username and password.

**Comment by emqplus** [comment]
@sphonala turn off the `allow_anonymous` in etc/emqx.conf

```
## Allow anonymous authentication by default if no auth plugins loaded.
## Notice: Disable the option in production deployment!
##
## Value: true | false
allow_anonymous = true
```

**Comment by sphonala** [comment]
yes, turned off and restarted emqx and rebooted also.
## Allow anonymous authentication by default if no auth plugins loaded.
## Notice: Disable the option in production deployment!
##
## Value: true | false
allow_anonymous = false

**Comment by emqplus** [comment]
@zhengyupan Please check the issue

**Comment by sphonala** [comment]
machine configuration:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

installed via repository
https://docs.emqx.io/broker/latest/en/install.html#ubuntu

**Comment by zhengyupan** [comment]
Hi @sphonala ,
Could you please let me know the EMQ X's version number and upload your conf files here, I will check.
Thank you!

**Comment by sphonala** [comment]
version emqx-4.0.1

https://we.tl/t-rmsCoYxFrB

**Comment by zhengyupan** [comment]
Hi @sphonala ,
If you use the auth_username to authenticate clients, the user info cannot be removed. if you want to remove a user, you will need to delete the contents in /var/lib/emqx/data/ and restart the service, then the db will be recreated.
We don't suggest using auth_username in production environment. For its simplicity, it may be good for functional test.

**Comment by emqplus** [comment]
@zhengyupan As I know, the `emqx_auth_username` plugin provides a CLI to remove the existed users. 

@sphonala Please try `users list` and `users del <Username>`

**Comment by zhengyupan** [comment]
@emqplus Thank you!

@sphonala please use `emqx_ctl` tool come with the emqx to delete user. 
To make the deletion permanent, you will need to

1. delete the user `emqx_ctl users del <username>`
2. remove the user from file `emqx_auth_username`

without the step 2, the user will be still able to connect after restart.

**Comment by sphonala** [comment]
Ok. Got it.

**Comment by HJianBo** [comment]
Hi, @sphonala Is the problem resolved?

**Comment by sphonala** [comment]
Hello @HJianBo, it's resolved.
