### ISSUE TITLE
Auth success when username and password are undefined 😅

### ISSUE THREAD

**Issue by saif7amed** [emqx/emqx-auth-username#150]
Hello,

Using Javascript `(mqtt.js)` and trying to login success due undefined `username` and `password`, if both are undefined, if only one of them, I get `Not Authorized` error.
![image](https://user-images.githubusercontent.com/62341575/88918675-e64efa00-d27a-11ea-8bbc-709379f34c95.png)

I checked if anonymous is allowed, and it is not:
![image](https://user-images.githubusercontent.com/62341575/88918099-f87c6880-d279-11ea-8e5a-add871eeec19.png)

**Comment by HJianBo** [comment]
Hi @saif7amed Could give me the emqx version and the loaded plugins list by `./bin/emqx_ctl plugins list|grep true`

**Comment by saif7amed** [comment]
Hi @HJianBo ,
I downloaded this [version](https://www.emqx.io/downloads#broker):
> sysdescr  : EMQ X Broker
version   : 4.1.1

Install it on (even if not listed as supported): 
> OS: Ubuntu 20.04

Here is the list of active plugins:

> Plugin(emqx_auth_username, description=EMQ X Authentication with Username and Password, active=true)
Plugin(emqx_bridge_mqtt, description=EMQ X Bridge to MQTT Broker, active=true)
Plugin(emqx_dashboard, description=EMQ X Web Dashboard, active=true)
Plugin(emqx_management, description=EMQ X Management API and CLI, active=true)
Plugin(emqx_recon, description=EMQ X Recon Plugin, active=true)
Plugin(emqx_retainer, description=EMQ X Retainer, active=true)
> Plugin(emqx_rule_engine, description=EMQ X Rule Engine, active=true)

Thank you for taking time to look into it 😄

**Comment by saif7amed** [comment]
Hi @HJianBo ,
After more tests, it allows access if both username and password are wrong, not sure why

Regards

**Comment by saif7amed** [comment]
restart the emqx solve this issue, maybe anonymous was allowed:

> emqx stop
emqx start

Thank you @HJianBo
