### ISSUE TITLE
[Plugins] cannot_find_plugins: emqx_auth_username

### ISSUE THREAD

**Issue by ctellechea2001** [emqx/emqx-auth-username#159]
https://github.com/emqx/emqx-rel/issues/656
https://github.com/emqx/emqx/issues/5352

We checked that with the same exactly configuration in V4.1.1 everything is working fine, but if I change to 4.3.5 We are getting errors the login failed for not autorized

dev-emqx-0 emqx 2021-07-29T20:00:27.023003+00:00 [warning] camara-08138281234@181.98.224.203:40412 [Channel] Client camara-08138281234 (Username: 'event-logger') **login failed for not_authorized**
dev-emqx-0 emqx 2021-07-29T20:00:27.023123+00:00 [debug] camara-08138281234@181.98.224.203:40412 **[MQTT] SEND CONNACK(Q0, R0, D0, AckFlags=0, ReasonCode=5)**
dev-emqx-0 emqx 2021-07-29T20:00:27.023322+00:00 [info] camara-08138281234@181.98.224.203:40412 file: emqx_connection.erl, line: 520, mfa: {emqx_connection,terminate,2}, msg: terminate, pid: <0.2570.0>, reason: {shutdown,not_authorized}

We discovered in the log files that in 4.3.5 is happening the following error. The emqx_auth_username was not loaded.

**2021-07-30T14:34:32.966151+00:00 [alert] [Plugins] cannot_find_plugins: [emqx_auth_username,emqx_statsd]**

emqx_auth_username.conf file with users is passing as parameters in the Helm Chart

         - name: emqx-users
            mountPath: /opt/emqx/etc/plugins/emqx_auth_username.conf
            subPath: emqx_auth_username.conf

Do you know what it is happening in the latest version with emqx_auth_username?

Inside the container

**/opt/emqx $ emqx_ctl plugins load emqx_auth_username
Load plugin emqx_auth_username error: not_found.
/opt/emqx $** 

Thanks!

**Comment by zmstone** [comment]
emqx_auth_username and emqx_auth_clientid are deleted from 4.3 release.
The functionalities are merged to emqx_auth_mnesia.

Please find more details here:
https://docs.emqx.io/en/broker/v4.3/changes/upgrade-4.3.html#upgrade-to-version-4-3
https://docs.emqx.io/en/broker/v4.3/advanced/auth-mnesia.html#authentication-rules

If you have a lot of data to upgrade, there are tools to help:
https://docs.emqx.io/en/broker/v4.3/advanced/data-import-and-export.html

**Comment by zmstone** [comment]
This repo is no longer used in EMQ X v4.3.
So I'm closing this issue here.
