### ISSUE TITLE
load plugin error: not_found

### ISSUE THREAD

**Issue by feature09** [emqx/emqx-auth-username#51]
when i exec:  
```
emqttd_ctl plugins load emq_auth_username.conf
```
the console:
```
load plugin error: not_found
```

**Comment by zhitingxie** [comment]
@feature09 is this issue fixed? I get this error just now, how to fix it? thanks!

**Comment by feature09** [comment]
i get this error cause of i didn't add 'plugins'.  sorry i couldn't help for you.
