### ISSUE TITLE
Not load at startup 

### ISSUE THREAD

**Issue by M3dS0** [emqx/emqx-auth-username#57]
Hello,

I've loaded and added some users with "emqx_ctl" and it's works perfectly, the problem is when i restart my server or emqx service this plugin will not start and even mqtt listener not gonna start, I should edit loadded_plugins and remove emqx_auth_username. and start again then load plugin manually.

**Comment by Gilbert-Wong** [comment]
Hi, @M3dS0 , it is exactly bug, I have fixed it in this pull  requesthttps://github.com/emqx/emqx-auth-username/pull/58

**Comment by M3dS0** [comment]
@Gilbert-Wong Thank you

**Comment by M3dS0** [comment]
currently I have no build environment, could you tell me when is the next release date?
