### ISSUE TITLE
emqx_auth_username   问题求解答

### ISSUE THREAD

**Issue by lrm929** [emqx/emqx-auth-username#59]
steps:

1  etit  emqx.conf 

      allow_anonymous = false

2  at web config  start emqx_auth_username  

3 cli run  ./bin/emqx stop 

4  next   ./bin/emqx start  
 tcp        0      0 0.0.0.0:6369                0.0.0.0:*                   LISTEN      12229/beam.smp      
tcp        0      0 0.0.0.0:18083               0.0.0.0:*                   LISTEN      12229/beam.smp      
tcp        0      0 0.0.0.0:8080                0.0.0.0:*                   LISTEN      12229/beam.smp      
tcp        0      0 0.0.0.0:5369                0.0.0.0:*                   LISTEN      12229/beam.smp    
Normally there should be many ports 
5 I'll use the command again.   ./bin/emqx stop 

error.log 
2018-12-19 14:26:25.670 [error] Plugin emqx_auth_username is not started

I don't know what the situation is.

**Comment by Gilbert-Wong** [comment]
Please open issue with English.

**Comment by lrm929** [comment]
emqx-centos6.8-v3.0-rc.5.zip

**Comment by lrm929** [comment]
If you stop "emqx_auth_username" in the web interface first, 
use cli  run. / bin / emqx stop
 cli run. / bin / emqx start   
so it's normal.

**Comment by lrm929** [comment]
OK, I'll try it.   Thanks   Gilbert-Wong

**Comment by lrm929** [comment]
emqx 3.0.0 release.    When can I download it?

**Comment by HJianBo** [comment]
Hi guys, the EMQX v3.0.0 has released in the long ago. You can download it [here](https://www.emqx.io/downloads)
